 # A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to
 # validate your config.  If you encounter any issues, please make an issue at
 # https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio          = [ 2, 7, 5 ]
sort_by        = "natural"
sort_sensitive = false
sort_reverse   = false
sort_dir_first = true
sort_translit  = false
linemode       = "none"
show_hidden    = false
show_symlink   = false
scrolloff      = 4
mouse_events   = [ "click", "scroll", "move", "drag" ]
title_format   = "Yazi: {cwd}"

[preview]
wrap            = "no"
tab_size        = 4
max_width       = 600
max_height      = 900
cache_dir       = ""
image_delay     = 30
image_filter    = "nearest"
image_quality   = 75
sixel_fraction  = 15
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[opener]

open = [
    { run = 'xdg-open "$1"', desc = "Open (XDG)",      for = "linux", orphan = true },
    { run = 'open "$@"',     desc = "Open",            for = "macos" },
    { run = 'start "" "%1"', desc = "Open",            for = "windows", orphan = true },

    { run = 'code "$@"',   desc = "Code",       for = "unix" },
    { run = 'code "%@"',   desc = "Code",       for = "windows" }
]

edit = [
    { run = '${EDITOR:-vi} "$@"', desc = "Use $EDITOR", for = "unix",    block = true },
    { run = 'vim "$1"',           desc = "Vim",         for = "unix",    block = true },
    { run = 'vim "%1"',           desc = "Vim",         for = "windows", block = true },
    { run = 'code "$@"',          desc = "Code",        for = "unix",    orphan = true },
    { run = 'code %*',            desc = "Code",        for = "windows", orphan = true }
]

view = [
    { run = 'vim -R "$1"', desc = "Vim (view)", for = "unix",    block = true},
    { run = 'vim -R "%1"', desc = "Vim (view)", for = "windows", block = true }
]

reveal = [
    { run = 'xdg-open "$(dirname "$1")"',           desc = "Reveal", for = "linux" },
    { run = 'open -R "$1"',                         desc = "Reveal", for = "macos" },
    { run = 'explorer /select,"%1"', orphan = true, desc = "Reveal", for = "windows" },
    { run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF", for = "unix" },
]

extract = [
    { run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
    { run = 'ya pub extract --list %*',   desc = "Extract here", for = "windows" },
]

play = [
    { run = 'mpv --force-window "$@"', orphan = true, for = "unix" },
    { run = 'mpv --force-window %*', orphan = true, for = "windows" },
    { run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info", for = "unix" },
]

pdf = [
    { run = 'okular "$@" &', desc = "Open with Okular", for = "linux", "orphan" = true },
    { run = 'qpdf --empty --pages "$@" -- merged.pdf', desc = "Merge PDFs", for = "linux", orphan = true },
    { run = 'zathura --fork "$@"', desc = "Open with Zathura", for = "linux", "orphan" = true },
]

image = [
	{ run = 'gimp "$@" &', desc = "GIMP", for = "linux", orphan = true },
	{ run = 'swappy -f "$@" -o "${@%.*}-edit.${@##*.}" &', desc = "Swappy", for = "linux", orphan = true },
]

qalc = [
    { run = 'qalc -f "$@" -i', desc = "Open with QALC", for = "linux", block = true },
]

[open]
rules = [
    # Empty file
    { mime = "inode/x-empty", use = [ "edit", "reveal" ] },
    # Folder
    { name = "*/", use = [ "edit", "open", "reveal" ] },

    # JSON
    { mime = "application/{json,x-ndjson}", use = [ "edit", "reveal" ] },
    { mime = "*/javascript", use = [ "edit", "reveal" ] },
    # PDF
    { mime = "application/pdf", use = [ "open", "pdf", "reveal" ] },

	# Images
	{ mime = "image/*", use = [ "open", "image", "reveal" ] },

    # QALC
    { name = "*.qalc", use = [ "edit", "qalc", "reveal" ] },

    # Text
    { mime = "text/html", use = [ "open", "edit", "reveal" ] },
    { mime = "text/*", use = [ "edit", "open", "reveal" ] },
    # Image
    { mime = "image/*", use = [ "open", "reveal" ] },
    # Media
    { mime = "{audio,video}/*", use = [ "play", "reveal" ] },
    # Archive
    { mime = "application/{,g}zip", use = [ "extract", "reveal" ] },
    { mime = "application/{tar,bzip*,7z-compressed,xz,rar}", use = [ "extract", "reveal" ] },

    # Fallback
    { name = "*", use = [ "open", "edit", "reveal" ] },
]

[tasks]
micro_workers    = 10
macro_workers    = 25
bizarre_retry    = 5
image_alloc      = 268435456  # 256MB
image_bound      = [ 0, 0 ]
suppress_preload = false

[plugin]

fetchers = [
    # Mimetype
    { id = "mime", name = "*", run = "mime", if = "!mime", prio = "high" },
    { id = "git", name = "*", run = "git" },
    { id = "git", name = "*/", run = "git" },
]

preloaders = [
    # Image
    { mime = "image/{avif,hei?,jxl,svg+xml}", run = "magick" },
    { mime = "image/*", run = "image" },
    # Video
    { mime = "video/*", run = "video" },
    # PDF
    { mime = "application/pdf", run = "pdf" },
    # Font
    { mime = "font/*", run = "font" },
    { mime = "application/vnd.ms-opentype", run = "font" },
]

previewers = [
    { name = "*/", run = "folder", sync = true },

    # Code
    { mime = "text/*", run = "code" },
    { mime = "*/{xml,javascript,x-wine-extension-ini}", run = "code" },

    # JSON
    { mime = "application/{json,x-ndjson}", run = "json" },

    # Image
    { mime = "image/{avif,hei?,jxl,svg+xml}", run = "magick" },
    { mime = "image/*", run = "image" },

    # Video
    { mime = "video/*", run = "video" },
    # PDF
    { mime = "application/pdf", run = "pdf" },

    # Archive
    { mime = "application/{,g}zip", run = "archive" },
    { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar,iso9660-image}", run = "archive" },

    # Font
    { mime = "font/*", run = "font" },
    { mime = "application/vnd.ms-opentype", run = "font" },

    # Empty file
    { mime = "inode/x-empty", run = "empty" },
    # Fallback
    { name = "*", run = "file" },
]

[input]
cursor_blink = false

# cd
cd_title  = "Change directory:"
cd_origin = "bottom-center"
cd_offset = [ 0, 2, 50, 3 ]

# create
create_title  = [ "Create:" , "Create dir:"]
create_origin = "bottom-center"
create_offset = [ 0, 2, 50, 3 ]

# rename
rename_title  = "Rename:"
rename_origin = "hovered"
rename_offset = [ 0, 1, 50, 3 ]

# filter
filter_title  = "Filter:"
filter_origin = "bottom-center"
filter_offset = [ 0, 2, 50, 3 ]

# find
find_title  = [ "Find next:", "Find previous:" ]
find_origin = "bottom-center"
find_offset = [ 0, 2, 50, 3 ]

# search
search_title  = "Search via {n}:"
search_origin = "bottom-center"
search_offset = [ 0, 2, 50, 3 ]

# shell
shell_title  = [ "Shell:", "Shell (block):" ]
shell_origin = "bottom-center"
shell_offset = [ 0, 2, 50, 3 ]

[confirm]
# trash
trash_title  = "Trash {n} selected file{s}?"
trash_origin = "center"
trash_offset = [ 0, 0, 70, 20 ]

# delete
delete_title  = "Permanently delete {n} selected file{s}?"
delete_origin = "center"
delete_offset = [ 0, 0, 70, 20 ]

# overwrite
overwrite_title   = "Overwrite file?"
overwrite_content = "Will overwrite the following file:"
overwrite_origin  = "center"
overwrite_offset  = [ 0, 0, 50, 15 ]

# quit
quit_title   = "Quit?"
quit_content = "The following task is still running, are you sure you want to quit?"
quit_origin  = "center"
quit_offset  = [ 0, 0, 50, 15 ]

[select]
open_title  = "Open with:"
open_origin = "hovered"
open_offset = [ 0, 1, 50, 7 ]

[which]
sort_by        = "none"
sort_sensitive = false
sort_reverse   = false
sort_translit  = false

[log]
enabled = false

